# See config.example.yml for documentation.
object_base: orig/GLME01
object: sys/main.dol
hash: 77d49225e7d28b9777916cdbe5809345c570ecbc
symbols: config/GLME01/symbols.txt
splits: config/GLME01/splits.txt
# Change this to match the linker verison.
# See config.example.yml for a list.
mw_comment_version: 8
