# See config.example.yml for documentation.
object_base: orig/GLMP01_01
object: sys/main.dol
hash: c9099665a33be49b16caa5c216c7e1094276c032
symbols: config/GLMP01_01/symbols.txt
splits: config/GLMP01_01/splits.txt
# Change this to match the linker verison.
# See config.example.yml for a list.
mw_comment_version: 8
