# See config.example.yml for documentation.
object_base: orig/GLMP01
object: sys/main.dol
hash: a1e2bd82813787cfe0b11afb5d138f08fdbd94f1
symbols: config/GLMP01/symbols.txt
splits: config/GLMP01/splits.txt
# Change this to match the linker verison.
# See config.example.yml for a list.
mw_comment_version: 8
